const data = [
  {
    id: 0,
    img:"завантаження.png",
    question: "В якому році була створена гра Brawl Stars?",
    variant1: "2018",
    variant2: "2017",
    variant3: "2009",
    variant4: "2019",
    answer: "variant1",
  },
  {
    id: 1,
    img:"Nita.jpeg",
    question: "Що це ща бравлер?",
    variant1: "шели",
    variant2: "френк",
    variant3: "нита",
    variant4: "бул",
    answer: "variant3",
  },
  {
    id: 2,
    img:"",
    question: "Хто зробив Brawl Stars?",
    variant1: "Ea sports",
    variant2: "Hayday",
    variant3: "Supercell",
    variant4: "Sports Danger",
    answer: "variant3",
  },
  {
    id: 3,
    img:"",
    question: "Як звати бравлера у якого ульта - щит?",
    variant1: "Нани",
    variant2: "Гриф",
    variant3: "Спайк",
    variant4: "Роза",
    answer: "variant4",
  },
  {
    id: 4,
    img:"static-assets-upload13904032638864390692.webp",
    question: "Скільки бравлерів в Brawl Stars?",
    variant1: "48",
    variant2: "79",
    variant3: "77",
    variant4: "78",
    answer: "variant2",
  },
  {
    id: 5,
    img:"1920х1080_12 (56)(2).jpg",
    question: "Назви бравлера який може літати ультою?",
    variant1: "Ворон",
    variant2: "Леон",
    variant3: "Сенди",
    variant4: "Мартис",
    answer: "variant1",
  },
];
export default data;
